const FROM_CLIENT_EVENT = {
  SENT_ENTER_ROOM_EVENT: 'SENT_ENTER_ROOM_EVENT',
  SENT_LEAVE_ROOM_EVENT: 'SENT_LEAVE_ROOM_EVENT',
  SENT_FULLSCREEN_EVENT: 'SENT_FULLSCREEN_EVENT',
  SENT_CALL_EVENT: 'SENT_CALL_EVENT',
  SENT_CANDIDATE: 'SENT_CANDIDATE',
  SENT_SDP: 'SENT_SDP',
  SENT_MOUSE_EVENT: 'SENT_MOUSE_EVENT',
};

const FROM_SERVER_EVENT = {
  RECEIVE_CONNECTED: 'RECEIVE_CONNECTED',
  RECEIVE_CALL: 'RECEIVE_CALL',
  RECEIVE_CANDIDATE: 'RECEIVE_CANDIDATE',
};

module.exports = {
  FROM_CLIENT_EVENT,
  FROM_SERVER_EVENT,
};
